In [17]:
from import_dados import *
pl.Config.set_tbl_rows(100)

polars.config.Config

In [62]:
pessoas = read_pessoas()
sinistros = trata_sinistros(read_sinistros())
veiculos = read_veiculos()

In [3]:
pessoas.null_count()

shape: (1, 31)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_sinist ┆ id_pessoa ┆ id_veicul ┆ cod_ibge ┆ … ┆ ano_mes_o ┆ local_obi ┆ local_via ┆ tempo_sin │
│ ro        ┆ ---       ┆ o         ┆ ---      ┆   ┆ bito      ┆ to        ┆ ---       ┆ istro_obi │
│ ---       ┆ u32       ┆ ---       ┆ u32      ┆   ┆ ---       ┆ ---       ┆ u32       ┆ to        │
│ u32       ┆           ┆ u32       ┆          ┆   ┆ u32       ┆ u32       ┆           ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ u32       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0         ┆ 0         ┆ 82887     ┆ 0        ┆ … ┆ 471890    ┆ 471890    ┆ 8734      ┆ 471890    │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
sinistros.join(pessoas, on='id_sinistro', how='anti').group_by('tipo_registro').len()

shape: (2, 2)
┌────────────────────┬──────┐
│ tipo_registro      ┆ len  │
│ ---                ┆ ---  │
│ str                ┆ u32  │
╞════════════════════╪══════╡
│ SINISTRO NAO FATAL ┆ 1768 │
│ NOTIFICACAO        ┆ 2730 │
└────────────────────┴──────┘

In [19]:
pessoas.with_columns(pl.col('tempo_sinistro_obito').is_not_null()).group_by('tipo_veiculo_vitima', 'modo_transporte_vitima', 'tempo_sinistro_obito').len().sort('tempo_sinistro_obito', 'len')

shape: (17, 4)
┌─────────────────────┬────────────────────────┬──────────────────────┬────────┐
│ tipo_veiculo_vitima ┆ modo_transporte_vitima ┆ tempo_sinistro_obito ┆ len    │
│ ---                 ┆ ---                    ┆ ---                  ┆ ---    │
│ str                 ┆ str                    ┆ bool                 ┆ u32    │
╞═════════════════════╪════════════════════════╪══════════════════════╪════════╡
│ NAO DISPONIVEL      ┆ NAO DISPONIVEL         ┆ false                ┆ 2      │
│ BICICLETA           ┆ BICICLETA              ┆ false                ┆ 18     │
│ OUTROS              ┆ OUTROS                 ┆ false                ┆ 5886   │
│ ONIBUS              ┆ ONIBUS                 ┆ false                ┆ 10996  │
│ CAMINHAO            ┆ CAMINHAO               ┆ false                ┆ 12954  │
│ null                ┆ PEDESTRE               ┆ false                ┆ 22621  │
│ null                ┆ null                   ┆ false                ┆ 57296  │
│ MOTOCICLETA         ┆ MOTOCICLETA            ┆ false                ┆ 173415 │
│ AUTOMOVEL           ┆ AUTOMOVEL              ┆ false                ┆ 188702 │
│ OUTROS              ┆ OUTROS                 ┆ true                 ┆ 63     │
│ ONIBUS              ┆ ONIBUS                 ┆ true                 ┆ 77     │
│ NAO DISPONIVEL      ┆ NAO DISPONIVEL         ┆ true                 ┆ 163    │
│ CAMINHAO            ┆ CAMINHAO               ┆ true                 ┆ 438    │
│ BICICLETA           ┆ BICICLETA              ┆ true                 ┆ 810    │
│ AUTOMOVEL           ┆ AUTOMOVEL              ┆ true                 ┆ 2671   │
│ null                ┆ PEDESTRE               ┆ true                 ┆ 2766   │
│ MOTOCICLETA         ┆ MOTOCICLETA            ┆ true                 ┆ 5315   │
└─────────────────────┴────────────────────────┴──────────────────────┴────────┘

In [48]:
pessoas.with_columns(pl.max('modo_transporte_vitima').over('id_sinistro').alias('max_modo')) \
    .filter(pl.col('modo_transporte_vitima').is_null()).group_by('gravidade_lesao').agg(pl.count('id_sinistro'), pl.count('max_modo'))

shape: (4, 3)
┌─────────────────┬─────────────┬──────────┐
│ gravidade_lesao ┆ id_sinistro ┆ max_modo │
│ ---             ┆ ---         ┆ ---      │
│ str             ┆ u32         ┆ u32      │
╞═════════════════╪═════════════╪══════════╡
│ NAO DISPONIVEL  ┆ 23565       ┆ 10582    │
│ LEVE            ┆ 14210       ┆ 10664    │
│ ILESO           ┆ 17734       ┆ 16058    │
│ GRAVE           ┆ 1787        ┆ 1262     │
└─────────────────┴─────────────┴──────────┘

In [87]:
pessoas.filter(pl.col('gravidade_lesao') == 'NAO DISPONIVEL')

shape: (25_664, 31)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_sinist ┆ id_pessoa ┆ id_veicul ┆ cod_ibge ┆ … ┆ ano_mes_o ┆ local_obi ┆ local_via ┆ tempo_sin │
│ ro        ┆ ---       ┆ o         ┆ ---      ┆   ┆ bito      ┆ to        ┆ ---       ┆ istro_obi │
│ ---       ┆ i64       ┆ ---       ┆ i64      ┆   ┆ ---       ┆ ---       ┆ str       ┆ to        │
│ i64       ┆           ┆ i64       ┆          ┆   ┆ str       ┆ str       ┆           ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ i64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1433051   ┆ 236903    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1791475   ┆ 691244    ┆ null      ┆ 3506102  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1742591   ┆ 500282    ┆ null      ┆ 3541000  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1410947   ┆ 209154    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1816856   ┆ 706717    ┆ null      ┆ 3552205  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1710441   ┆ 514006    ┆ null      ┆ 3521309  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1710441   ┆ 682888    ┆ null      ┆ 3521309  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1673197   ┆ 497028    ┆ null      ┆ 3541406  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1509343   ┆ 401266    ┆ null      ┆ 3514403  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1651340   ┆ 542970    ┆ null      ┆ 3537404  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1509343   ┆ 283938    ┆ null      ┆ 3514403  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1651340   ┆ 434206    ┆ null      ┆ 3537404  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1622185   ┆ 425378    ┆ null      ┆ 3548906  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1695056   ┆ 598084    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1836412   ┆ 546901    ┆ null      ┆ 3541406  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1849619   ┆ 593712    ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1698821   ┆ 468026    ┆ null      ┆ 3545803  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1586794   ┆ 443822    ┆ null      ┆ 3522109  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1822947   ┆ 757726    ┆ null      ┆ 3518701  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1280168   ┆ 87946     ┆ null      ┆ 3530607  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1729579   ┆ 670427    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1772736   ┆ 748828    ┆ null      ┆ 3552205  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1318935   ┆ 124987    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1583096   ┆ 366388    ┆ null      ┆ 3543303  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2459376   ┆ 6744      ┆ null      ┆ 3514304  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 1516290   ┆ 322812    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1746709   ┆ 494985    ┆ null      ┆ 3555406  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2093124   ┆ 1050873   ┆ null      ┆ 3534401  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2006956   ┆ 805173    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2503931   ┆ 67884     ┆ null      ┆ 3525904  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 1614233   ┆ 367277    ┆ null      ┆ 3509502  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1828621   ┆ 750884    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2468891   ┆ 25370     ┆ null      ┆ 3549805  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2503931   ┆ 72752     ┆ null      ┆ 3525904  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2503931   ┆ 62840     ┆ null      ┆ 3525904  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2464142   ┆ 11756     ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2503931   ┆ 74221     ┆ null      ┆ 3525904  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2468383   ┆ 20647     ┆ null      ┆ 3503950  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 1852613   ┆ 799053    ┆ null      ┆ 3552809  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1939638   ┆ 759298    ┆ null      ┆ 3518404  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1615315   ┆ 370438    ┆ null      ┆ 3555406  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1705616   ┆ 611154    ┆ null      ┆ 3541000  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1715760   ┆ 516371    ┆ null      ┆ 3519600  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1804577   ┆ 607213    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2214334   ┆ 1104281   ┆ null      ┆ 3552205  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2497451   ┆ 68430     ┆ null      ┆ 3529807  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2257012   ┆ 1080198   ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1717295   ┆ 507020    ┆ null      ┆ 3516309  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2490325   ┆ 44673     ┆ null      ┆ 3515004  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2497451   ┆ 66732     ┆ null      ┆ 3529807  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2725395   ┆ 920995    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2717771   ┆ 399534    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2712628   ┆ 145500    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711392   ┆ 22464     ┆ null      ┆ 3550100  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711392   ┆ 21449     ┆ null      ┆ 3550100  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2717968   ┆ 440812    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711391   ┆ 21022     ┆ null      ┆ 3532603  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2715363   ┆ 276324    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711391   ┆ 24565     ┆ null      ┆ 3532603  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711621   ┆ 63296     ┆ null      ┆ 3541000  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711285   ┆ 10959     ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711285   ┆ 7272      ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711285   ┆ 12869     ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711428   ┆ 29730     ┆ null      ┆ 3502507  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2724704   ┆ 1885832   ┆ null      ┆ 3549805  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2711387   ┆ 27057     ┆ null      ┆ 3502309  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2717761   ┆ 430542    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2719225   ┆ 529150    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2719225   ┆ 718696    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711674   ┆ 61851     ┆ null      ┆ 3551009  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711662   ┆ 56905     ┆ null      ┆ 3536505  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2720603   ┆ 634559    ┆ null      ┆ 3548708  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711431   ┆ 41524     ┆ null      ┆ 3508504  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2723200   ┆ 956902    ┆ null      ┆ 3552502  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2727878   ┆ 962390    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2727101   ┆ 1119366   ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2711274   ┆ 7499      ┆ null      ┆ 3549904  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2728153   ┆ 14550     ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711288   ┆ 12046     ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2717130   ┆ 454146    ┆ null      ┆ 3529401  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711710   ┆ 71134     ┆ null      ┆ 3509502  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2719924   ┆ 718829    ┆ null      ┆ 3515004  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2724133   ┆ 683003    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711582   ┆ 44721     ┆ null      ┆ 3550704  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711582   ┆ 57617     ┆ null      ┆ 3550704  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2723740   ┆ 1030772   ┆ 2990858   ┆ 3517307  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2711700   ┆ 68466     ┆ null      ┆ 3543907  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711700   ┆ 79896     ┆ null      ┆ 3543907  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2711700   ┆ 77159     ┆ null      ┆ 3543907  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2719307   ┆ 577618    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2719307   ┆ 471726    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2711799   ┆ 67154     ┆ null      ┆ 3526902  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2717425   ┆ 366567    ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2717425   ┆ 371292    ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2717425   ┆ 459019    ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2728248   ┆ 38595     ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2728248   ┆ 32285     ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2728248   ┆ 37635     ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2728248   ┆ 35062     ┆ null      ┆ 3547809  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2722609   ┆ 737883    ┆ null      ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [88]:
pessoas.filter(pl.col('id_sinistro') == 2723740)

shape: (1, 31)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_sinist ┆ id_pessoa ┆ id_veicul ┆ cod_ibge ┆ … ┆ ano_mes_o ┆ local_obi ┆ local_via ┆ tempo_sin │
│ ro        ┆ ---       ┆ o         ┆ ---      ┆   ┆ bito      ┆ to        ┆ ---       ┆ istro_obi │
│ ---       ┆ i64       ┆ ---       ┆ i64      ┆   ┆ ---       ┆ ---       ┆ str       ┆ to        │
│ i64       ┆           ┆ i64       ┆          ┆   ┆ str       ┆ str       ┆           ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ i64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2723740   ┆ 1030772   ┆ 2990858   ┆ 3517307  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [89]:
sinistros.filter(pl.col('id_sinistro') == 2723740)

shape: (0, 54)
┌─────────────┬─────────────┬─────────────┬─────────────┬───┬──────┬────────┬────────────┬─────────┐
│ id_sinistro ┆ tipo_regist ┆ data_sinist ┆ ano_sinistr ┆ … ┆ hora ┆ minuto ┆ acidente_f ┆ literal │
│ ---         ┆ ro          ┆ ro          ┆ o           ┆   ┆ ---  ┆ ---    ┆ atal       ┆ ---     │
│ i64         ┆ ---         ┆ ---         ┆ ---         ┆   ┆ i16  ┆ i16    ┆ ---        ┆ str     │
│             ┆ str         ┆ str         ┆ i64         ┆   ┆      ┆        ┆ str        ┆         │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══╪══════╪════════╪════════════╪═════════╡
└─────────────┴─────────────┴─────────────┴─────────────┴───┴──────┴────────┴────────────┴─────────┘

In [64]:
pessoas.filter(pl.col('tipo_de_vitima') == 'NAO DISPONIVEL') \
.group_by('id_sinistro').agg(pl.col('gravidade_lesao')).filter(pl.col('gravidade_lesao').list.len() == 1)\
.join(sinistros, on='id_sinistro')

shape: (7_062, 55)
┌─────────────┬─────────────┬────────────┬────────────┬───┬──────┬────────┬────────────┬───────────┐
│ id_sinistro ┆ gravidade_l ┆ tipo_regis ┆ data_sinis ┆ … ┆ hora ┆ minuto ┆ acidente_f ┆ literal   │
│ ---         ┆ esao        ┆ tro        ┆ tro        ┆   ┆ ---  ┆ ---    ┆ atal       ┆ ---       │
│ i64         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ i16  ┆ i16    ┆ ---        ┆ str       │
│             ┆ list[str]   ┆ str        ┆ str        ┆   ┆      ┆        ┆ str        ┆           │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪══════╪════════╪════════════╪═══════════╡
│ 2464142     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 21   ┆ 10     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2506531     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 10   ┆ 26     ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1821022     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 02/01/2024 ┆ … ┆ 6    ┆ 1      ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2459376     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 17   ┆ 10     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2487037     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 02/01/2024 ┆ … ┆ 18   ┆ 20     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1303184     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 02/01/2024 ┆ … ┆ 16   ┆ 48     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1471412     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 8    ┆ 59     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2468383     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 1    ┆ 0      ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2490325     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 9    ┆ 4      ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2500176     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 12   ┆ null   ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2468891     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 01/01/2024 ┆ … ┆ 7    ┆ 45     ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2465565     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 08/01/2024 ┆ … ┆ 6    ┆ 0      ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2054268     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 10   ┆ 11     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1979356     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 07/01/2024 ┆ … ┆ 2    ┆ 28     ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2013570     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 07/01/2024 ┆ … ┆ 4    ┆ 4      ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2490380     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 08/01/2024 ┆ … ┆ 5    ┆ 55     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1271496     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 08/01/2024 ┆ … ┆ 14   ┆ 25     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1451257     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 08/01/2024 ┆ … ┆ 17   ┆ 11     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1927591     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 09/01/2024 ┆ … ┆ 8    ┆ 22     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2479611     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 22   ┆ 45     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1566265     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 20   ┆ 15     ┆ NAO        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1995055     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 10   ┆ 58     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1976284     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 03/01/2024 ┆ … ┆ 10   ┆ 44     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1629053     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 07/01/2024 ┆ … ┆ 16   ┆ 24     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1464240     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 10/01/2024 ┆ … ┆ 16   ┆ 23     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2480658     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 12/01/2024 ┆ … ┆ 0    ┆ 58     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2480980     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 12/01/2024 ┆ … ┆ 13   ┆ 15     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1321322     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 12/01/2024 ┆ … ┆ 15   ┆ 1      ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1544800     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 07/01/2024 ┆ … ┆ 13   ┆ 49     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2116225     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 07/01/2024 ┆ … ┆ 4    ┆ 43     ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1846696     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 09/01/2024 ┆ … ┆ 7    ┆ 32     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1471187     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 10/01/2024 ┆ … ┆ 16   ┆ 37     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1476904     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 12/01/2024 ┆ … ┆ 17   ┆ 39     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1550327     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 05/01/2024 ┆ … ┆ 19   ┆ 36     ┆ NAO        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2151888     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 07/01/2024 ┆ … ┆ 6    ┆ 21     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1558217     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 10/01/2024 ┆ … ┆ 18   ┆ 29     ┆ NAO        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1831604     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 10/01/2024 ┆ … ┆ 5    ┆ 46     ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2458230     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 12/01/2024 ┆ … ┆ 21   ┆ 50     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1949729     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 09/01/2024 ┆ … ┆ 8    ┆ 50     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1882874     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 7    ┆ 5      ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 1361456     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 17   ┆ 24     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2491146     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 05/01/2024 ┆ … ┆ 17   ┆ 10     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2457840     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 06/01/2024 ┆ … ┆ 2    ┆ 35     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2095451     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 10/01/2024 ┆ … ┆ 9    ┆ 12     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2489245     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 12/01/2024 ┆ … ┆ 12   ┆ 18     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2193112     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 05/01/2024 ┆ … ┆ 14   ┆ 16     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2507331     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 10/01/2024 ┆ … ┆ 4    ┆ 24     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2151239     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 14   ┆ 13     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2007485     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 11/01/2024 ┆ … ┆ 10   ┆ 35     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2507198     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 12/01/2024 ┆ … ┆ 20   ┆ 0      ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ …           ┆ …           ┆ …          ┆ …          ┆ … ┆ …    ┆ …      ┆ …          ┆ …         │
│ 2711581     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 25/12/2025 ┆ … ┆ 6    ┆ 0      ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711464     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 20/12/2025 ┆ … ┆ 5    ┆ 30     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2717349     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 21/12/2025 ┆ … ┆ 14   ┆ 42     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711405     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 21/12/2025 ┆ … ┆ 7    ┆ 25     ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711413     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 23/12/2025 ┆ … ┆ 14   ┆ 15     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711829     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 25/12/2025 ┆ … ┆ 0    ┆ 31     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711524     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 25/12/2025 ┆ … ┆ 6    ┆ 37     ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711484     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 19/12/2025 ┆ … ┆ 22   ┆ 9      ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2721852     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 24/12/2025 ┆ … ┆ 3    ┆ 0      ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2720109     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 25/12/2025 ┆ … ┆ 15   ┆ 27     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711588     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 19/12/2025 ┆ … ┆ 10   ┆ 22     ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711350     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 20/12/2025 ┆ … ┆ 12   ┆ 39     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711553     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 20/12/2025 ┆ … ┆ 5    ┆ 30     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711395     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 23/12/2025 ┆ … ┆ 17   ┆ 0      ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2719959     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 25/12/2025 ┆ … ┆ 18   ┆ 7      ┆ NAO        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2728413     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 20/12/2025 ┆ … ┆ 8    ┆ 50     ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711264     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 20/12/2025 ┆ … ┆ 18   ┆ 21     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2717055     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 20/12/2025 ┆ … ┆ 15   ┆ 29     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711906     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 21/12/2025 ┆ … ┆ 8    ┆ 20     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2725455     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 22/12/2025 ┆ … ┆ 9    ┆ 36     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711400     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 25/12/2025 ┆ … ┆ 0    ┆ 20     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711655     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 26/12/2025 ┆ … ┆ 17   ┆ 10     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711314     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 19/12/2025 ┆ … ┆ 12   ┆ 18     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2723333     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 20/12/2025 ┆ … ┆ 4    ┆ 45     ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2728337     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 21/12/2025 ┆ … ┆ 23   ┆ 4      ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2720578     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 21/12/2025 ┆ … ┆ 17   ┆ 32     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2720643     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 22/12/2025 ┆ … ┆ 22   ┆ 55     ┆ NAO        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711492     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 23/12/2025 ┆ … ┆ 18   ┆ 59     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2722659     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 23/12/2025 ┆ … ┆ 9    ┆ 41     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2714003     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 25/12/2025 ┆ … ┆ 4    ┆ 1      ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711674     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 28/12/2025 ┆ … ┆ 14   ┆ 32     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711621     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 27/12/2025 ┆ … ┆ 3    ┆ 24     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2717771     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 27/12/2025 ┆ … ┆ 19   ┆ 20     ┆ NAO        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2720603     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 28/12/2025 ┆ … ┆ 1    ┆ 41     ┆ NAO        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711288     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 28/12/2025 ┆ … ┆ 8    ┆ 0      ┆ SIM        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711662     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 28/12/2025 ┆ … ┆ 19   ┆ 19     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2728153     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 28/12/2025 ┆ … ┆ 19   ┆ 0      ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2727878     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 28/12/2025 ┆ … ┆ 9    ┆ 57     ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711710     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 29/12/2025 ┆ … ┆ 16   ┆ 52     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2722609     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 31/12/2025 ┆ … ┆ 8    ┆ 1      ┆ NAO        ┆ MANHA     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711428     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 27/12/2025 ┆ … ┆ 0    ┆ 10     ┆ SIM        ┆ MADRUGADA │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2715363     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 27/12/2025 ┆ … ┆ 16   ┆ 16     ┆ NAO        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ NAO FATAL  ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711274     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 28/12/2025 ┆ … ┆ 21   ┆ 33     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711799     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 31/12/2025 ┆ … ┆ 12   ┆ 30     ┆ SIM        ┆ TARDE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │
│ 2711387     ┆ ["NAO DISPO ┆ SINISTRO   ┆ 27/12/2025 ┆ … ┆ 20   ┆ 36     ┆ SIM        ┆ NOITE     │
│             ┆ NIVEL"]     ┆ FATAL      ┆            ┆   ┆      ┆        ┆            ┆           │

In [85]:
pessoas.join(sinistros.select('id_sinistro', 'tipo_registro'), on='id_sinistro')
.join().group_by('tipo_registro', 'id_sinistro') \
    .agg(pl.col('id_veiculo').drop_nulls(), pl.col('id_pessoa')) \
    .filter(pl.col('id_veiculo').list.len() == 0)

shape: (9_244, 4)
┌────────────────────┬─────────────┬────────────┬─────────────────────────────┐
│ tipo_registro      ┆ id_sinistro ┆ id_veiculo ┆ id_pessoa                   │
│ ---                ┆ ---         ┆ ---        ┆ ---                         │
│ str                ┆ i64         ┆ list[i64]  ┆ list[i64]                   │
╞════════════════════╪═════════════╪════════════╪═════════════════════════════╡
│ NOTIFICACAO        ┆ 2165191     ┆ []         ┆ [1082953]                   │
│ NOTIFICACAO        ┆ 2368279     ┆ []         ┆ [1108421]                   │
│ SINISTRO NAO FATAL ┆ 2639323     ┆ []         ┆ [1785841]                   │
│ NOTIFICACAO        ┆ 2288009     ┆ []         ┆ [357160, 1373194]           │
│ NOTIFICACAO        ┆ 2271742     ┆ []         ┆ [1167216, 125056, 1167215]  │
│ SINISTRO NAO FATAL ┆ 2426639     ┆ []         ┆ [396975, 481794]            │
│ SINISTRO NAO FATAL ┆ 2433211     ┆ []         ┆ [510638, 552293]            │
│ SINISTRO FATAL     ┆ 2628353     ┆ []         ┆ [63245]                     │
│ SINISTRO NAO FATAL ┆ 2298878     ┆ []         ┆ [417521, 336193, 415653]    │
│ SINISTRO FATAL     ┆ 2483527     ┆ []         ┆ [47233]                     │
│ SINISTRO FATAL     ┆ 2558890     ┆ []         ┆ [28301]                     │
│ NOTIFICACAO        ┆ 2362860     ┆ []         ┆ [849484]                    │
│ NOTIFICACAO        ┆ 2393616     ┆ []         ┆ [1270846, 317033]           │
│ SINISTRO FATAL     ┆ 2487560     ┆ []         ┆ [44656]                     │
│ NOTIFICACAO        ┆ 2563069     ┆ []         ┆ [257421, 364090]            │
│ SINISTRO FATAL     ┆ 2594984     ┆ []         ┆ [13225]                     │
│ SINISTRO FATAL     ┆ 2482980     ┆ []         ┆ [39967]                     │
│ SINISTRO FATAL     ┆ 2458520     ┆ []         ┆ [3676]                      │
│ NOTIFICACAO        ┆ 2637554     ┆ []         ┆ [1566840, 690789]           │
│ SINISTRO FATAL     ┆ 2661797     ┆ []         ┆ [58605]                     │
│ SINISTRO FATAL     ┆ 2644760     ┆ []         ┆ [8186]                      │
│ SINISTRO NAO FATAL ┆ 1682091     ┆ []         ┆ [477951]                    │
│ SINISTRO FATAL     ┆ 2461771     ┆ []         ┆ [8717]                      │
│ NOTIFICACAO        ┆ 2267834     ┆ []         ┆ [1176216, 162093]           │
│ NOTIFICACAO        ┆ 2630354     ┆ []         ┆ [1196023]                   │
│ SINISTRO NAO FATAL ┆ 1609090     ┆ []         ┆ [388427, 530340]            │
│ NOTIFICACAO        ┆ 2582419     ┆ []         ┆ [283765]                    │
│ NOTIFICACAO        ┆ 2304451     ┆ []         ┆ [701481]                    │
│ NOTIFICACAO        ┆ 2641986     ┆ []         ┆ [1063005]                   │
│ SINISTRO NAO FATAL ┆ 2411655     ┆ []         ┆ [1167090]                   │
│ NOTIFICACAO        ┆ 2361211     ┆ []         ┆ [1069685, 1877156]          │
│ SINISTRO NAO FATAL ┆ 2440868     ┆ []         ┆ [834105, 893477]            │
│ SINISTRO FATAL     ┆ 2579621     ┆ []         ┆ [24535]                     │
│ SINISTRO NAO FATAL ┆ 2369722     ┆ []         ┆ [942516, 1930825, … 922839] │
│ SINISTRO NAO FATAL ┆ 2420257     ┆ []         ┆ [355514]                    │
│ SINISTRO NAO FATAL ┆ 2711169     ┆ []         ┆ [970844]                    │
│ NOTIFICACAO        ┆ 2315029     ┆ []         ┆ [1614701, 648251]           │
│ NOTIFICACAO        ┆ 2359735     ┆ []         ┆ [795485, 795043]            │
│ NOTIFICACAO        ┆ 2356190     ┆ []         ┆ [920505]                    │
│ SINISTRO NAO FATAL ┆ 2270452     ┆ []         ┆ [157350, 129193]            │
│ SINISTRO FATAL     ┆ 2479030     ┆ []         ┆ [37010]                     │
│ NOTIFICACAO        ┆ 2329064     ┆ []         ┆ [783594]                    │
│ SINISTRO NAO FATAL ┆ 2525287     ┆ []         ┆ [917159]                    │
│ NOTIFICACAO        ┆ 2635329     ┆ []         ┆ [502679]                    │
│ SINISTRO FATAL     ┆ 2545942     ┆ []         ┆ [37778]                     │
│ SINISTRO NAO FATAL ┆ 2670047     ┆ []         ┆ [486839, 434885, 1417031]   │
│ SINISTRO FATAL     ┆ 2468200     ┆ []         ┆ [16990]                     │
│ NOTIFICACAO        ┆ 2322391     ┆ []         ┆ [1690419, 882535]           │
│ SINISTRO NAO FATAL ┆ 1582523     ┆ []         ┆ [385920]                    │
│ SINISTRO NAO FATAL ┆ 2436320     ┆ []         ┆ [608584, 771379, 1563681]   │
│ …                  ┆ …           ┆ …          ┆ …                           │
│ NOTIFICACAO        ┆ 2264690     ┆ []         ┆ [76463, 88326]              │
│ SINISTRO NAO FATAL ┆ 2583834     ┆ []         ┆ [380638]                    │
│ SINISTRO NAO FATAL ┆ 2677915     ┆ []         ┆ [1056029, 1849872, 750121]  │
│ SINISTRO FATAL     ┆ 2594965     ┆ []         ┆ [8811]                      │
│ SINISTRO NAO FATAL ┆ 2347939     ┆ []         ┆ [954994]                    │
│ NOTIFICACAO        ┆ 2430411     ┆ []         ┆ [442187, 1469089]           │
│ NOTIFICACAO        ┆ 2603464     ┆ []         ┆ [511643]                    │
│ SINISTRO NAO FATAL ┆ 2368454     ┆ []         ┆ [911274]                    │
│ NOTIFICACAO        ┆ 2275398     ┆ []         ┆ [1253198]                   │
│ NOTIFICACAO        ┆ 2640871     ┆ []         ┆ [799158, 1889373, 1889374]  │
│ SINISTRO NAO FATAL ┆ 2383921     ┆ []         ┆ [694607]                    │
│ NOTIFICACAO        ┆ 2386098     ┆ []         ┆ [924611]                    │
│ SINISTRO NAO FATAL ┆ 2287121     ┆ []         ┆ [338225, 1287724]           │
│ NOTIFICACAO        ┆ 2416399     ┆ []         ┆ [280255]                    │
│ NOTIFICACAO        ┆ 2745798     ┆ []         ┆ [1015133, 1773791]          │
│ SINISTRO FATAL     ┆ 2477446     ┆ []         ┆ [35228]                     │
│ SINISTRO FATAL     ┆ 2506125     ┆ []         ┆ [68177]                     │
│ SINISTRO FATAL     ┆ 2579736     ┆ []         ┆ [32656]                     │
│ NOTIFICACAO        ┆ 2634368     ┆ []         ┆ [1440974, 576948]           │
│ SINISTRO NAO FATAL ┆ 2580439     ┆ []         ┆ [132865]                    │
│ NOTIFICACAO        ┆ 2361929     ┆ []         ┆ [1071129, 780111]           │
│ SINISTRO NAO FATAL ┆ 2285292     ┆ []         ┆ [272279]                    │
│ SINISTRO NAO FATAL ┆ 2327616     ┆ []         ┆ [563571, 716384]            │
│ NOTIFICACAO        ┆ 2511591     ┆ []         ┆ [256672]                    │
│ SINISTRO FATAL     ┆ 2579872     ┆ []         ┆ [52994, 68971]              │
│ NOTIFICACAO        ┆ 2515676     ┆ []         ┆ [455337, 628950]            │
│ NOTIFICACAO        ┆ 2233401     ┆ []         ┆ [991458]                    │
│ SINISTRO FATAL     ┆ 2711350     ┆ []         ┆ [15015, 17466]              │
│ NOTIFICACAO        ┆ 2593734     ┆ []         ┆ [990736]                    │
│ SINISTRO FATAL     ┆ 2501105     ┆ []         ┆ [73880]                     │
│ NOTIFICACAO        ┆ 1806113     ┆ []         ┆ [579663]                    │
│ SINISTRO NAO FATAL ┆ 2667420     ┆ []         ┆ [386134]                    │
│ NOTIFICACAO        ┆ 2416118     ┆ []         ┆ [199373]                    │
│ NOTIFICACAO        ┆ 2414989     ┆ []         ┆ [255077]                    │
│ SINISTRO NAO FATAL ┆ 2523253     ┆ []         ┆ [1020109]                   │
│ SINISTRO NAO FATAL ┆ 2619489     ┆ []         ┆ [466828]                    │
│ SINISTRO NAO FATAL ┆ 2673313     ┆ []         ┆ [531904]                    │
│ SINISTRO NAO FATAL ┆ 2373778     ┆ []         ┆ [1023071]                   │
│ SINISTRO FATAL     ┆ 2559246     ┆ []         ┆ [73454]                     │
│ NOTIFICACAO        ┆ 2575959     ┆ []         ┆ [867183]                    │
│ SINISTRO FATAL     ┆ 2471029     ┆ []         ┆ [28409]                     │
│ SINISTRO FATAL     ┆ 2579627     ┆ []         ┆ [25120]                     │
│ SINISTRO NAO FATAL ┆ 2566191     ┆ []         ┆ [383984, 1419099, 542147]   │
│ SINISTRO NAO FATAL ┆ 2630192     ┆ []         ┆ [182892]                    │
│ NOTIFICACAO        ┆ 2574395     ┆ []         ┆ [1053502, 1847306]          │
│ NOTIFICACAO        ┆ 2300280     ┆ []         ┆ [353070]                    │
│ SINISTRO FATAL     ┆ 2481509     ┆ []         ┆ [40094, 37161]              │
│ SINISTRO FATAL     ┆ 2628256     ┆ []         ┆ [60008]                     │
│ NOTIFICACAO        ┆ 1593377     ┆ []         ┆ [420243]                    │
│ NOTIFICACAO        ┆ 2597639     ┆ []         ┆ [222449, 176483]            │
└────────────────────┴─────────────┴────────────┴─────────────────────────────┘

In [86]:
sinistros.filter(pl.col('id_sinistro') == 2677915)

shape: (1, 54)
┌─────────────┬─────────────┬────────────┬────────────┬───┬──────┬────────┬────────────┬───────────┐
│ id_sinistro ┆ tipo_regist ┆ data_sinis ┆ ano_sinist ┆ … ┆ hora ┆ minuto ┆ acidente_f ┆ literal   │
│ ---         ┆ ro          ┆ tro        ┆ ro         ┆   ┆ ---  ┆ ---    ┆ atal       ┆ ---       │
│ i64         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ i16  ┆ i16    ┆ ---        ┆ str       │
│             ┆ str         ┆ str        ┆ i64        ┆   ┆      ┆        ┆ str        ┆           │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪══════╪════════╪════════════╪═══════════╡
│ 2677915     ┆ SINISTRO    ┆ 25/09/2025 ┆ 2025       ┆ … ┆ 1    ┆ 10     ┆ NAO        ┆ MADRUGADA │
│             ┆ NAO FATAL   ┆            ┆            ┆   ┆      ┆        ┆            ┆           │
└─────────────┴─────────────┴────────────┴────────────┴───┴──────┴────────┴────────────┴───────────┘