In [1]:
import polars as pl
from import_dados import *

In [2]:
df_veiculos = read_veiculos()

In [8]:
df_veiculos.filter(pl.col('ano_sinistro') == 2025).group_by('tipo_veiculo').agg(pl.count().alias('qtd_veiculos'))

C:\Users\aliss\AppData\Local\Temp\ipykernel_5100\583319514.py:1: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  df_veiculos.filter(pl.col('ano_sinistro') == 2025).group_by('tipo_veiculo').agg(pl.count().alias('qtd_veiculos'))

shape: (7, 2)
┌────────────────┬──────────────┐
│ tipo_veiculo   ┆ qtd_veiculos │
│ ---            ┆ ---          │
│ str            ┆ u32          │
╞════════════════╪══════════════╡
│ BICICLETA      ┆ 3842         │
│ AUTOMOVEL      ┆ 80829        │
│ OUTROS         ┆ 6010         │
│ CAMINHAO       ┆ 7283         │
│ NAO DISPONIVEL ┆ 5476         │
│ MOTOCICLETA    ┆ 73790        │
│ ONIBUS         ┆ 4439         │
└────────────────┴──────────────┘

In [ ]:
faixa_inicio = ((pl.col('ano_fab') - 2001) // 5 * 5 + 2001)

(df_veiculos
    .with_columns(
        pl.when(pl.col('ano_fab').is_between(1900, 1970))
        .then(pl.lit('1900-1970'))
        .when(pl.col('ano_fab').is_between(1971, 2000))
        .then(pl.lit('1971-2000'))
        .when(pl.col('ano_fab') >= 2001)
        .then(pl.format('{}-{}', faixa_inicio, faixa_inicio + 4))
        .otherwise(pl.lit('Fora do intervalo'))
        .alias('faixa_fabricacao')
    )
    .group_by('faixa_fabricacao')
    .agg(pl.len().alias('qtd_veiculos'))
    .sort('qtd_veiculos', descending=True).filter(pl.col('faixa_fabricacao') != "Fora do intervalo")
)

shape: (8, 2)
┌───────────────────┬──────────────┐
│ faixa_fabricacao  ┆ qtd_veiculos │
│ ---               ┆ ---          │
│ str               ┆ u32          │
╞═══════════════════╪══════════════╡
│ 2021-2025         ┆ 92663        │
│ 2011-2015         ┆ 77391        │
│ 2016-2020         ┆ 71922        │
│ Fora do intervalo ┆ 65769        │
│ 2006-2010         ┆ 61893        │
│ 2001-2005         ┆ 24496        │
│ 1971-2000         ┆ 24053        │
│ 1900-1970         ┆ 152          │
└───────────────────┴──────────────┘