In [1]:
from import_dados import *

In [2]:
pessoas = read_pessoas()
sinistros = read_sinistros()

In [6]:
pessoas.null_count()

shape: (1, 31)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_sinist ┆ id_pessoa ┆ id_veicul ┆ cod_ibge ┆ … ┆ ano_mes_o ┆ local_obi ┆ local_via ┆ tempo_sin │
│ ro        ┆ ---       ┆ o         ┆ ---      ┆   ┆ bito      ┆ to        ┆ ---       ┆ istro_obi │
│ ---       ┆ u32       ┆ ---       ┆ u32      ┆   ┆ ---       ┆ ---       ┆ u32       ┆ to        │
│ u32       ┆           ┆ u32       ┆          ┆   ┆ u32       ┆ u32       ┆           ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ u32       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0         ┆ 0         ┆ 82887     ┆ 0        ┆ … ┆ 471890    ┆ 471890    ┆ 8734      ┆ 471890    │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
pessoas.group_by('tipo_de_vitima').len()

shape: (4, 2)
┌────────────────┬────────┐
│ tipo_de_vitima ┆ len    │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ CONDUTOR       ┆ 237465 │
│ PASSAGEIRO     ┆ 171615 │
│ PEDESTRE       ┆ 25387  │
│ NAO DISPONIVEL ┆ 49726  │
└────────────────┴────────┘

In [ ]:
sinistros.join(pessoas, on='id_sinistro', how='full') \
    .filter(pl.col('tipo_registro') != 'NOTIFICACAO') \
    .group_by('tipo_de_vitima').len()

shape: (5, 2)
┌────────────────┬────────┐
│ tipo_de_vitima ┆ len    │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ null           ┆ 2717   │
│ NAO DISPONIVEL ┆ 49047  │
│ PASSAGEIRO     ┆ 169510 │
│ PEDESTRE       ┆ 22373  │
│ CONDUTOR       ┆ 236552 │
└────────────────┴────────┘

In [16]:
sinistros.join(pessoas, on='id_sinistro', how='full') \
    .filter(pl.col('id_pessoa').is_null()) \
    .group_by('tipo_registro').len()

shape: (2, 2)
┌────────────────────┬────────┐
│ tipo_registro      ┆ len    │
│ ---                ┆ ---    │
│ str                ┆ u32    │
╞════════════════════╪════════╡
│ SINISTRO NAO FATAL ┆ 2717   │
│ NOTIFICACAO        ┆ 146653 │
└────────────────────┴────────┘