In [3]:
%run import_dados.py

In [5]:
pessoas = read_pessoas()

In [6]:
pessoas

shape: (484_193, 31)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_sinist ┆ id_pessoa ┆ id_veicul ┆ cod_ibge ┆ … ┆ ano_mes_o ┆ local_obi ┆ local_via ┆ tempo_sin │
│ ro        ┆ ---       ┆ o         ┆ ---      ┆   ┆ bito      ┆ to        ┆ ---       ┆ istro_obi │
│ ---       ┆ i64       ┆ ---       ┆ i64      ┆   ┆ ---       ┆ ---       ┆ str       ┆ to        │
│ i64       ┆           ┆ i64       ┆          ┆   ┆ str       ┆ str       ┆           ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ i64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2207150   ┆ 957330    ┆ 1374212   ┆ 3534401  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1714622   ┆ 518803    ┆ 709427    ┆ 3519071  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 1856857   ┆ 1595645   ┆ 2660377   ┆ 3552403  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 1410947   ┆ 1243476   ┆ 337438    ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 1410947   ┆ 207616    ┆ 337438    ┆ 3550308  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2722180   ┆ 947087    ┆ 2987788   ┆ 3543907  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2723625   ┆ 1043980   ┆ 2989308   ┆ 3541000  ┆ … ┆ null      ┆ null      ┆ NAO DISPO ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ NIVEL     ┆           │
│ 2727330   ┆ 1872364   ┆ 2990056   ┆ 3534401  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2721040   ┆ 1528304   ┆ 2985370   ┆ 3514403  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
│ 2727330   ┆ 1872365   ┆ null      ┆ 3534401  ┆ … ┆ null      ┆ null      ┆ PUBLICO   ┆ null      │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [29]:
pessoas \
.withColumn('pessoas_veiculo', f.count('id_pessoa').over(Window.partitionBy('id_veiculo'))) \
.filter(f.col('pessoas_veiculo') == 1) \
.groupBy('tipo_veiculo_vitima').count() \
.toPandas()

  tipo_veiculo_vitima  count
0         MOTOCICLETA  53058
1              OUTROS   2201
2      NAO DISPONIVEL      3
3            CAMINHAO   3481
4              ONIBUS   4682
5           AUTOMOVEL  57914
6           BICICLETA    174

In [ ]:
pessoas.filter(f.col('tipo_de_vitima') == 'NAO DISPONIVEL')

   tipo_de_vitima  count
0  NAO DISPONIVEL  20644
1      PASSAGEIRO  76956
2        PEDESTRE  14776
3        CONDUTOR  84396

In [19]:
pessoas \
    .filter(f.col('tipo_de_vitima') == 'NAO DISPONIVEL'). \
    groupBy('tipo_de_vitima', 'gravidade_lesao').count().toPandas()

   tipo_de_vitima gravidade_lesao  count
0  NAO DISPONIVEL           ILESO   8631
1  NAO DISPONIVEL            LEVE   2090
2  NAO DISPONIVEL           FATAL    172
3  NAO DISPONIVEL  NAO DISPONIVEL   9541
4  NAO DISPONIVEL           GRAVE    210